name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [latest]
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies ðŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }} ðŸš€
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm ðŸš€
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.5
          run_install: false

      - name: Install dependencies ðŸš€
        run: pnpm install

      - name: test âœ¨
        run: pnpm run test
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
